image: node:carbon

stages:
  - init
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

init:
  stage: init
  tags:
    - shell
  script:
    - echo init success
  only:
    - master

build:
  stage: build
  tags:
    - docker
  script:
    - yarn
    - npm run build
  variables:
    VUE_APP_PUBLIC_PATH: /ife/
    VUE_APP_ROUTER_MODE: history
  artifacts:
    paths:
      - dist/
  only:
    - master

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - mkdir -p /var/www/ife
    - cp -r ./dist/* /var/www/ife/
  dependencies:
    - build
  only:
    - master
