language: node_js
node_js:
  - '10'
install:
  # install node-canvas dependencies
  - sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
  - yarn
jobs:
  include:
    - stage: Test
      script:
        - yarn test
    - stage: Deploy
      if: branch = master
      script:
        - yarn build
        - cp ./dist/index.html ./dist/404.html
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: ./dist
cache: yarn
addons:
  apt:
    update: true
