language: node_js
node_js:
  - '10'
install:
  # install node-canvas dependencies
  - sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
  - yarn
script:
 - yarn test
cache: yarn
addons:
  apt:
    update: true
